Updated the yml file to new Moshe file

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -27,6 +27,7 @@ jobs:
         path: image.tar
 
     - name: Upload log file
+      if: ${{ always() }}
       uses: actions/upload-artifact@v3
       with:
         name: log
@@ -39,49 +40,57 @@ jobs:
     - name: Check out repository
       uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
+    - name: Download log file
+      if: ${{ always() }}
+      uses: actions/download-artifact@v3
       with:
-        python-version: 3.9
+        name: log
+        path: previous-log
+
+    - name: Merge log files
+      run: |
+        cat previous-log/log.txt >> log.txt
+
+    - name: Set up Python
+      uses: actions/setup-python@v4
+
 
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pytest requests
 
-    - name: Download log file for testing purposes
-      uses: actions/download-artifact@v3
-      with:
-        name: log
-        path: tmp
-
     - name: Download Docker image
       uses: actions/download-artifact@v3
       with:
         name: docker-image
-        path: tmp
+        path: .
 
     - name: Load Docker image
-      run: docker load --input /home/runner/work/Cloud-Computing-And-Software-Engineering-HW3-main/Cloud-Computing-And-Software-Engineering-HW3-main/tmp/image.tar
-
+      run: docker load --input image.tar
 
     - name: Run Docker container
       run: |
-        docker run -d --name my-service-container -p 8000:8000 my-service
-
-
+        docker run -d --name my-service-container -p8000:8000 my-service
+      #&& echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)
 
     - name: Run Pytest
-      run:
-        pytest -v tests/assn3_tests.py
+      run: pytest -v tests/assn3_tests.py | tee assn3_test_results.txt
+      continue-on-error: true
+
+    - name: Check test results
+      run: |
+        if grep -q "failed" assn3_test_results.txt; then echo "tests failed" >> log.txt; exit 1; else echo "tests succeeded" >> log.txt; fi
 
     - name: Upload updated log file
+      if: ${{ always() }}
       uses: actions/upload-artifact@v3
       with:
         name: log
         path: log.txt
 
-    - name: Upload updated log file
+    - name: Upload test results
+      if: ${{ always() }}
       uses: actions/upload-artifact@v3
       with:
         name: assn3_test_results
@@ -95,15 +104,25 @@ jobs:
     - name: Check out repository
       uses: actions/checkout@v3
 
+    - name: Download log file
+      if: ${{ always() }}
+      uses: actions/download-artifact@v3
+      with:
+        name: log
+        path: previous-log
+
+    - name: Merge log files
+      run: |
+        cat previous-log/log.txt >> log.txt
+
     - name: Download Docker image
       uses: actions/download-artifact@v3
       with:
         name: docker-image
-        path: tmp
+        path: .
 
     - name: Load Docker image
-      run: docker load --input /home/runner/work/Cloud-Computing-And-Software-Engineering-HW3-main/Cloud-Computing-And-Software-Engineering-HW3-main/tmp/image.tar
-
+      run: docker load --input image.tar
 
     - name: Run Docker container
       run: |
@@ -127,3 +146,10 @@ jobs:
       with:
         name: query-results
         path: response.txt
+
+    - name: Upload updated log file
+      if: ${{ always() }}
+      uses: actions/upload-artifact@v3
+      with:
+        name: log
+        path: log.txt
