Updated yml file to new Moshes version

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -16,7 +16,7 @@ jobs:
       id: build-image
       run: |
         echo "$(date --iso-8601=minutes)" > log.txt
-        echo "Yehontan Eliyahu Moshe Azulay" >> log.txt
+        echo "Yehonatan Elyahu Moshe Azulay" >> log.txt
         docker build -t my-service . && echo "image successfully built" >> log.txt || (echo "image not able to be built" >> log.txt && exit 1)
         docker save my-service -o image.tar
 
@@ -72,7 +72,17 @@ jobs:
     - name: Run Docker container
       run: |
         docker run --name my-service-container -p8000:8000 my-service &
-      #&& echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)
+
+    - name: Check container status
+      if: always()
+      run: |
+          if [ "$( docker container inspect -f '{{.State.Running}}' my-service-container )" = "true" ]; then
+            echo "Container is up and running" >> log.txt
+          else
+            echo "Container failed to run" >> log.txt
+            exit 1
+          fi
+        
 
     - name: Run Pytest
       run: pytest -v tests/assn3_tests.py | tee assn3_test_results.txt
@@ -104,17 +114,6 @@ jobs:
     - name: Check out repository
       uses: actions/checkout@v3
 
-    - name: Download log file
-      if: ${{ always() }}
-      uses: actions/download-artifact@v3
-      with:
-        name: log
-        path: previous-log
-
-    - name: Merge log files
-      run: |
-        cat previous-log/log.txt >> log.txt
-
     - name: Download Docker image
       uses: actions/download-artifact@v3
       with:
@@ -126,12 +125,11 @@ jobs:
 
     - name: Run Docker container
       run: |
-        docker run -d --name my-service-container -p 8000:8000 my-service
+        docker run --name my-service-container -p8000:8000 my-service &
 
     - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
+      uses: actions/setup-python@v4
+
 
     - name: Install dependencies
       run: |
@@ -142,14 +140,8 @@ jobs:
       run: python query.py
 
     - name: Upload query results
+      if: ${{ always() }}
       uses: actions/upload-artifact@v3
       with:
         name: query-results
         path: response.txt
-
-    - name: Upload updated log file
-      if: ${{ always() }}
-      uses: actions/upload-artifact@v3
-      with:
-        name: log
-        path: log.txt
