trigger for debug

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -1,123 +1,124 @@
-#name: assignment3
-#
-#on:
-#  push:
-#    branches: [ master ]
-#
-#jobs:
-#  build:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#    - name: Check out repository
-#      uses: actions/checkout@v3
-#
-#    - name: Build Docker image
-#      id: build-image
-#      run: |
-#        echo "$(date --iso-8601=minutes)" > log.txt
-#        echo "Yehontan Eliyahu Moshe Azulay" >> log.txt
-#        docker build -t my-service . && echo "image successfully built" >> log.txt || (echo "image not able to be built" >> log.txt && exit 1)
-#        docker save my-service -o image.tar
-#
-##    - name: Upload Docker image
-##      uses: actions/upload-artifact@v3
-##      with:
-##        name: docker-image
-##        path: /tmp/image.tar
-#
-#
-#    - name: Upload log file
+name: assignment3
+
+on:
+  push:
+    branches: [ master ]
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v3
+
+    - name: Build Docker image
+      id: build-image
+      run: |
+        echo "$(date --iso-8601=minutes)" > log.txt
+        echo "Yehontan Eliyahu Moshe Azulay" >> log.txt
+        docker build -t my-service . && echo "image successfully built" >> log.txt || (echo "image not able to be built" >> log.txt && exit 1)
+        docker save my-service -o image.tar
+
+#    - name: Upload Docker image
 #      uses: actions/upload-artifact@v3
-#      with:
-#        name: log
-#        path: log.txt
-#
-#  test:
-#    needs: build
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#    - name: Download log file for testing purposes
-#      uses: actions/download-artifact@v3
-#      with:
-#        name: log.txt
-#
-#    - name: Download Docker image
-#      uses: actions/download-artifact@v3
 #      with:
 #        name: docker-image
-#        path: /tmp
-#
-#    - name: Load Docker image
-#      run: docker load --input docker-image/tmp/image.tar
-#
-#
-#    - name: Run Docker container
-#      run: |
-#        docker run -d --name my-service-container -p 8000:8000 my-service && echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)
-#
-#    - name: Set up Python
-#      uses: actions/setup-python@v2
-#      with:
-#        python-version: 3.8
-#
-#    - name: Install dependencies
-#      run: |
-#        python -m pip install --upgrade pip
-#        pip install pytest
-#
-#    - name: Run Pytest
-#      run: |
-#        pytest -v tests/assn3_tests.py > assn3_test_results.txt && echo "tests succeeded" >> log.txt || (echo "tests failed" >> log.txt && exit 1)
-#
-#    - name: Upload pytest results
-#      uses: actions/upload-artifact@v3
-#      with:
-#        name: pytest-results
-#        path: assn3_test_results.txt
-#
-#    - name: Upload updated log file
-#      uses: actions/upload-artifact@v3
-#      with:
-#        name: log
-#        path: log.txt
-#
-#  query:
-#    needs: build
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#    - name: Check out repository
-#      uses: actions/checkout@v3
-#
-#    - name: Download Docker image
-#      uses: actions/download-artifact@v3
-#      with:
-#        name: docker-image
-#
-#    - name: Load Docker image
-#      run: docker load -i docker-image/image.tar
-#
-#    - name: Run Docker container
-#      run: |
-#        docker run -d --name my-service-container -p 8000:8000 my-service
-#
-#    - name: Set up Python
-#      uses: actions/setup-python@v2
-#      with:
-#        python-version: 3.8
-#
-#    - name: Install dependencies
-#      run: |
-#        python -m pip install --upgrade pip
-#        pip install requests
-#
-#    - name: Query the service
-#      run: python query_script.py
-#
-#    - name: Upload query results
-#      uses: actions/upload-artifact@v3
-#      with:
-#        name: query-results
-#        path: response.txt
+#        path: /tmp/image.tar
+
+
+    - name: Upload log file
+      uses: actions/upload-artifact@v3
+      with:
+        name: log
+        path: log.txt
+
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Download log file for testing purposes
+      uses: actions/download-artifact@v3
+      with:
+        name: log.txt
+        path: tmp
+
+    - name: Download Docker image
+      uses: actions/download-artifact@v3
+      with:
+        name: docker-image
+        path: tmp
+
+    - name: Load Docker image
+      run: docker load --input docker-image/tmp/image.tar
+
+
+    - name: Run Docker container
+      run: |
+        docker run -d --name my-service-container -p 8000:8000 my-service && echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pytest
+
+    - name: Run Pytest
+      run: |
+        pytest -v tests/assn3_tests.py > assn3_test_results.txt && echo "tests succeeded" >> log.txt || (echo "tests failed" >> log.txt && exit 1)
+
+    - name: Upload pytest results
+      uses: actions/upload-artifact@v3
+      with:
+        name: pytest-results
+        path: assn3_test_results.txt
+
+    - name: Upload updated log file
+      uses: actions/upload-artifact@v3
+      with:
+        name: log
+        path: log.txt
+
+  query:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v3
+
+    - name: Download Docker image
+      uses: actions/download-artifact@v3
+      with:
+        name: docker-image
+
+    - name: Load Docker image
+      run: docker load -i docker-image/image.tar
+
+    - name: Run Docker container
+      run: |
+        docker run -d --name my-service-container -p 8000:8000 my-service
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install requests
+
+    - name: Query the service
+      run: python query_script.py
+
+    - name: Upload query results
+      uses: actions/upload-artifact@v3
+      with:
+        name: query-results
+        path: response.txt
